# Use an official Node runtime as a parent image
FROM node:14-alpine

# Set the working directory to /app
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install dependencies
RUN npm install --only=production

# Copy the rest of the app to the working directory
COPY . .

# Set environment variables
ENV NODE_ENV production
ENV PORT 8000

# Expose port 8000
EXPOSE 8000

# Start the app
CMD [ "npm", "start" ]