---
- hosts: your_remote_host
  become: true
  tasks:
    - name: Update and upgrade the system
      apt:
        update_cache: yes
        upgrade: dist

    - name: Add Node.js repository key
      apt_key:
        url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
        state: present

    - name: Add Node.js repository
      apt_repository:
        repo: deb https://deb.nodesource.com/{{ ansible_distribution|lower }}_{{ ansible_distribution_release }} main
        state: present
        filename: nodesource.list

    - name: Install Node.js LTS
      apt:
        name: nodejs
        state: present
        update_cache: yes

    - name: Install Nginx
      apt:
        name: nginx
        state: present
        update_cache: yes

    - name: Configure Nginx
      lineinfile:
        path: /etc/nginx/sites-available/default
        line: |
          server {
              listen 80 default_server;
              server_name _;

              location / {
                  proxy_pass http://localhost:3000;
              }

              location /api {
                  proxy_pass http://localhost:8000;
              }
          }
      notify:
        - Restart Nginx

    - name: Reload firewall
      ufw:
        state: reloaded

  handlers:
    - name: Restart Nginx
      systemd:
        name: nginx
        state: restarted
