---
- hosts: your_remote_host
  become: true
  tasks:
    - name: Update and upgrade the system
      apt:
        update_cache: yes
        upgrade: dist

    - name: Add Node.js repository key
      apt_key:
        url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
        state: present

    - name: Add Node.js repository
      apt_repository:
        repo: deb https://deb.nodesource.com/{{ ansible_distribution|lower }}_{{ ansible_distribution_release }} main
        state: present
        filename: nodesource.list

    - name: Install Node.js LTS
      apt:
        name: nodejs
        state: present
        update_cache: yes

    - name: Install Nginx
      apt:
        name: nginx
        state: present
        update_cache: yes

    - name: Configure Nginx
      systemd:
        name: nginx
        state: started
        enabled: yes

    - name: Install PM2
      npm:
        name: pm2
        global: yes

    - name: Configure firewall
      ufw:
        rule: "{{ item }}"
        state: present
      loop:
        - name: allow SSH
          rule: allow
          port: 22
        - name: allow HTTP
          rule: allow
          port: 80
        - name: allow HTTPS
          rule: allow
          port: 443
        - name: allow Nginx Full
          rule: allow
          port: 80,443

    - name: Reload firewall
      ufw:
        state: reloaded
